services:
  pgsql:
    image: postgres:alpine
    ports:
      - '5433:5432'
    container_name: 'pgsqlReactomatic'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reactomatic
volumes:
  pg-data: