services:
  pgsql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pgsqlReactomatic'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin_reactomatic
      POSTGRES_PASSWORD: RlSNVOnUmcz7VSrj
      POSTGRES_DB: reactomatic
volumes:
  pg-data:
