export enum ComponentType {
    PROCESSOR = 'PROCESSOR',
    MOTHERBOARD = 'MOTHERBOARD',
    GPU = 'GPU',
    VENTIRAD = 'VENTIRAD',
    MEMORY = 'MEMORY',
    STORAGE = 'STORAGE',
    EXTERNALDEVICE = 'EXTERNALDEVICE',
    CASE = 'CASE',
    POWERSUPPLY = 'POWERSUPPLY',
}
