export enum ComponentType {
    case_accessory = 'case_accessory',
    case_fan = 'case_fan',
    case = 'case',
    cpu_cooler = 'cpu_cooler',
    cpu = 'cpu',
    external_hard_drive = 'external_hard_drive',
    internal_hard_drive = 'internal_hard_drive',
    fan_controller = 'fan_controller',
    headphones = 'headphones',
    keyboard = 'keyboard',
    memory = 'memory',
    monitor = 'monitor',
    motherboard = 'motherboard',
    mouse = 'mouse',
    optical_drive = 'optical_drive',
    os = 'os',
    power_supply = 'power_supply',
    sound_card = 'sound_card',
    speakers = 'speakers',
    thermal_paste = 'thermal_paste',
    ups = 'ups',
    video_card = 'video_card',
    webcam = 'webcam',
    wired_network_card = 'wired_network_card',
    wireless_network_card = 'wireless_network_card',

}