export enum ComponentType {
    PROCESSOR = 'PROCESSOR_ID',
    MOTHERBOARD = 'MOTHERBOARD_ID',
    GPU = 'GPU_ID',
    VENTIRAD = 'VENTIRAD_ID',
    MEMORY = 'MEMORY_ID',
    STORAGE = 'STORAGE_ID',
    EXTERNALDEVICE = 'EXTERNALDEVICE_ID',
    CASE = 'CASE_ID',
    POWERSUPPLY = 'POWERSUPPLY_ID',
}
